sudo: false
dist: trusty
language: cpp
compiler:
  - gcc

# command to run tests
script: 
  - gcc --version
  - mkdir build
  - cd build
  - cmake ..
  - make

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang
    - python-dev
    - cmake
