environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.8"
      PYTHON_ARCH: "64"
      PIP: "C:\\Python36-x64\\Scripts\\pip"

# Operating system (build VM template)
os: Visual Studio 2017
platform: x64
configuration: 
  - Release
  - Debug

# scripts that are called at very beginning, before repo cloning
init:
  - chcp 65001
  # For remote debugging
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# clone directory
clone_folder: c:\projects\story-project

# scripts to run before build
before_build:
  - cd c:\projects\story-project
  - set PYTHONIOENCODING=utf-8

  - echo Set python environment ...
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -V

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "%PYTHON%\\python.exe -m pip install --disable-pip-version-check --user --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

  - echo Running cmake ...
  - mkdir build
  - cd build 
  - cmake .. -A x64 -DCMAKE_BUILD_TYPE=%CONFIGURATION%

build:
  project: c:\projects\story-project\build\story-project.sln

# scripts to run after build
after_build:

install:
  # by default, all script lines are interpreted as batch

# on_finish:
  # For remote debugging
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
