version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic
    environment:
      - CC: gcc-7
      - CXX: g++-7

    steps:
      - checkout
      - run:
          name: Prepare build environments
          command: |
            sudo apt update && \
            sudo apt install -y \
              software-properties-common \
              build-essential cmake \
              python3-pip

      - run:
          name: Build
          command: |
            cmake --version && \
            python3 --version && \
            pip3 install -r requirements.txt && \
            mkdir -p build && cd build && \
            cmake .. -DCMAKE_BUILD_TYPE=Release && \
            cmake --build . --config Release --parallel 2
