version: 2
jobs:
  build:
    working_directory: ~/story
    docker:
      - image: circleci/buildpack-deps:bionic
    environment:
      - CC: gcc-7
      - CXX: g++-7

    steps:
      - checkout
      - run:
          name: Prepare build environments
          command: |
            sudo apt update && \
            sudo apt install -y software-properties-common && \
            wget --no-check-certificate -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add - && \
            sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main' && \
            sudo apt update && sudo apt install -y \
              xvfb mesa-common-dev \
              libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev \
              build-essential cmake \
              python3-pip && \
            cmake --version && \
            python3 --version && \
            mkdir -p ~/story/build

      - run:
          name: Generates cache
          working_directory: ~/story/external
          command: |
            pip3 install -r ../requirements.txt && \
            python3 ./external_build.py --gen-cache

      - restore_cache:
          keys:
            - story-external-scripts-{{ checksum "external/script.cache" }}
            # if cache for exact version of `project.clj` is not present then load any most recent one
            - story-external-scripts-

      - run:
          name: Build
          working_directory: ~/story/build
          command: |
            cmake .. -DCMAKE_BUILD_TYPE=Release && \
            cmake --build . --config Release --parallel 2 --target story-project

      - run:
          name: Build & Perform tests
          working_directory: ~/story/build
          command: |
            cmake --build . --config Release --parallel 2 --target story-test &&
            ./story-test || true

      - save_cache:
          key: story-external-scripts-{{ checksum "external/script.cache" }}
          paths:
            - /home/circleci/story/external/build
