# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ipc.proto',
  package='ipc',
  syntax='proto3',
  serialized_pb=_b('\n\tipc.proto\x12\x03ipc\"\xdf\x01\n\nIPCMessage\x12\x0b\n\x03pid\x18\x01 \x01(\x05\x12)\n\x04item\x18\x02 \x03(\x0b\x32\x1b.ipc.IPCMessage.MessageItem\x1a\x46\n\x0bMessageItem\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.ipc.IPCMessage.MessageType\x12\x0c\n\x04text\x18\x02 \x01(\t\"Q\n\x0bMessageType\x12\x11\n\rGET_SCENEINFO\x10\x00\x12\x11\n\rSET_SCENEINFO\x10\x01\x12\r\n\tLOG_DEBUG\x10\x02\x12\r\n\tLOG_ERROR\x10\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_IPCMESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='ipc.IPCMessage.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET_SCENEINFO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_SCENEINFO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOG_DEBUG', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOG_ERROR', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=161,
  serialized_end=242,
)
_sym_db.RegisterEnumDescriptor(_IPCMESSAGE_MESSAGETYPE)


_IPCMESSAGE_MESSAGEITEM = _descriptor.Descriptor(
  name='MessageItem',
  full_name='ipc.IPCMessage.MessageItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ipc.IPCMessage.MessageItem.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='ipc.IPCMessage.MessageItem.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=159,
)

_IPCMESSAGE = _descriptor.Descriptor(
  name='IPCMessage',
  full_name='ipc.IPCMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='ipc.IPCMessage.pid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item', full_name='ipc.IPCMessage.item', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_IPCMESSAGE_MESSAGEITEM, ],
  enum_types=[
    _IPCMESSAGE_MESSAGETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=242,
)

_IPCMESSAGE_MESSAGEITEM.fields_by_name['type'].enum_type = _IPCMESSAGE_MESSAGETYPE
_IPCMESSAGE_MESSAGEITEM.containing_type = _IPCMESSAGE
_IPCMESSAGE.fields_by_name['item'].message_type = _IPCMESSAGE_MESSAGEITEM
_IPCMESSAGE_MESSAGETYPE.containing_type = _IPCMESSAGE
DESCRIPTOR.message_types_by_name['IPCMessage'] = _IPCMESSAGE

IPCMessage = _reflection.GeneratedProtocolMessageType('IPCMessage', (_message.Message,), dict(

  MessageItem = _reflection.GeneratedProtocolMessageType('MessageItem', (_message.Message,), dict(
    DESCRIPTOR = _IPCMESSAGE_MESSAGEITEM,
    __module__ = 'ipc_pb2'
    # @@protoc_insertion_point(class_scope:ipc.IPCMessage.MessageItem)
    ))
  ,
  DESCRIPTOR = _IPCMESSAGE,
  __module__ = 'ipc_pb2'
  # @@protoc_insertion_point(class_scope:ipc.IPCMessage)
  ))
_sym_db.RegisterMessage(IPCMessage)
_sym_db.RegisterMessage(IPCMessage.MessageItem)


# @@protoc_insertion_point(module_scope)
